# Databricks App execution (app.yaml). Required at project root.
# Docs: https://docs.databricks.com/aws/en/dev-tools/databricks-apps/app-runtime
# App definition (resources, bindings): resources/fastapi_app.yml. When deployed, the platform runs this in source_code_path and proxies traffic to the app.
# User auth: open from Compute → Apps → payment-analysis so the platform forwards your token (x-forwarded-access-token). Set PGAPPNAME and DATABRICKS_WAREHOUSE_ID in app Environment; DATABRICKS_HOST is optional when opened from Apps.
command:
  - uvicorn
  - payment_analysis.backend.app:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"
env:
  - name: PYTHONPATH
    value: src
  - name: PGAPPNAME
    value: payment-analysis-db-dev
