# Databricks App execution (app.yaml). Required at project root.
# Docs: https://docs.databricks.com/aws/en/dev-tools/databricks-apps/app-runtime
# App definition (resources, bindings): resources/fastapi_app.yml. When deployed, the platform runs this in source_code_path and proxies traffic to the app.
# User auth: open from Compute → Apps → payment-analysis so the platform forwards your token (x-forwarded-access-token).
# Service principal: the app uses the service principal (e.g. fb1b1b8f-b3f6-45e1-b62c-c9e7d483526d) to execute actions on behalf of the app when DATABRICKS_CLIENT_ID and DATABRICKS_CLIENT_SECRET are set (injected by the platform in app Environment).
# Lakebase: set LAKEBASE_PROJECT_ID, LAKEBASE_BRANCH_ID, LAKEBASE_ENDPOINT_ID in app Environment (Compute → Apps → Edit → Environment); same values as Job 1 create_lakebase_autoscaling. Set DATABRICKS_WAREHOUSE_ID; DATABRICKS_HOST is optional when opened from Apps.
command:
  - uvicorn
  - payment_analysis.backend.app:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"
env:
  - name: PYTHONPATH
    value: src
  # Lakebase Autoscaling (set in app Environment; example defaults below)
  - name: LAKEBASE_PROJECT_ID
    value: payment-analysis-db
  - name: LAKEBASE_BRANCH_ID
    value: production
  - name: LAKEBASE_ENDPOINT_ID
    value: primary
