# Runtime spec (same as app.yaml). Required at root for "error loading app spec from app.yml".
# See https://apps-cookbook.dev/docs/fastapi/getting_started/create
command: ["uvicorn", "app:app"]
env:
  - name: PYTHONPATH
    value: src
  - name: PGAPPNAME
    value: payment-analysis-db-dev
