# =============================================================================
# Databricks App - Payment Approval Optimization Platform
# =============================================================================
# Deploys the app (FastAPI + React UI) to Databricks Apps. After bundle deploy,
# run the app via Workspace → Apps or: databricks bundle run payment_analysis_app -t dev
# App URL is shown in bundle summary or in Workspace → Apps.
# =============================================================================

resources:
  apps:
    payment_analysis_app:
      name: payment-analysis
      source_code_path: ..
      description: Payment Approval Optimization Platform – dashboards, rules, decisioning, ML models, and agent jobs.
      # Set PGAPPNAME in the app env (Workspace → Apps → app → Edit → Environment) to the Lakebase instance name (dev: payment-analysis-db-dev).
